server {
    listen 80;
    listen [::]:80;
    server_name carabetta.xyz www.carabetta.xyz;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://carabetta.xyz$request_uri;
    }

    access_log /var/log/nginx/carabetta-access.log;
    error_log /var/log/nginx/carabetta-error.log;
}
